### PR TITLE
update to python3.10 #22 #23

### PR DESCRIPTION
**Pull request by wu-clan**
Please note that this pr does not work properly and needs to be checked and repaired.

### CODE REVIEW

**Comment by downdawn** [comment]
Every py file needs to import annotations, isn't it a bit intrusive?

Isn't using TYPE_CHECKING a bit too harsh?

**Comment by wu-clan** [comment]
Annotation is already the default behavior in 3.10, and there is no need to import it manually.

Can refuse to use TYPE_CHECKING, but it seems that there will be a little performance optimization?

They can be managed through ruff. It works very well.

**Comment by downdawn** [comment]
Yes, so I prefer 3.10

For the time being, we can ignore TYPE_CHECKING the performance improvements that come with type_checking, which should be simple and efficient.

ruff works well, and I've looked at their documentation

**Comment by wu-clan** [comment]
No problem, let‘s start directly from 3.10. People who like it also need 3.10, and need to add it to readme as a reminder.

**Comment by wu-clan** [comment]
I’d be happy if you could update the code directly. 

I can‘t code it for the time being these days……

**Comment by wu-clan** [comment]
Thank you for @downdawn PR #29

**Pull request closed without merging**
