### PR TITLE
add rbac authorization

### PR DESCRIPTION
**Pull request by wu-clan**
WIP.

Please note that the table structure has been redesigned, is significantly different from the previous one, and is **not forward compatible**

### CODE REVIEW

**Review by downdawn — APPROVED** [review]

**Comment by wu-clan** [comment]
WIP.

**Comment by wu-clan** [comment]
WIP.

**Comment by wu-clan** [comment]
Hi, @downdawn 

please review!

Other TODO works will start in other medium processes

**Review by downdawn — APPROVED** [review]

**Comment by downdawn** [comment]
GTM

**Pull request merged**
