### PR TITLE
Add ItsDangerous request parameters encryption

### PR DESCRIPTION
**Pull request by wu-clan**
PLR.

### CODE REVIEW

**Review by downdawn — APPROVED** [review]

**Comment by downdawn** [comment]
AES decryption seems to have some problems

**Comment by wu-clan** [comment]
Encryption and decryption need to be used in conjunction with this, which is an MRE
```python
from backend.app.utils.encrypt import AESCipher, ItsDCipher

pwd = '123456'

aes = AESCipher('d77b25790a804c2b4a339dd0207941e4cefa5751935a33735bc73bb7071a005b')
its = ItsDCipher('d77b25790a804c2b4a339dd0207941e4cefa5751935a33735bc73bb7071a005b')

ae_pwd = aes.encrypt(pwd).hex()

ad_pwd = aes.decrypt(ae_pwd)

ie_pwd = its.encrypt(pwd)

id_pwd = its.decrypt(ie_pwd)

if __name__ == '__main__':
    print(f'pwd: {pwd}')
    print(f'ae_pwd: {ae_pwd}')
    print(f'ad_pwd: {ad_pwd}')
    print(f'ie_pwd: {ie_pwd}')
    print(f'id_pwd: {id_pwd}')
```

Result:
```
pwd: 123456
ae_pwd: 51a41fff02344b74732b842eebb7ae9cf4a5368072e494785e7264566498c460
ad_pwd: b'123456'
ie_pwd: IjEyMzQ1NiI.612bAIP8GFxXHl7YQoGH9m0UNfM
id_pwd: 123456
```

The difference is that AES decryption returns the bytes

**Comment by wu-clan** [comment]
AES decryption now returns as a string

**Comment by downdawn** [comment]
Why should key and encryption and decryption be converted to hexadecimal?
Shouldn't normal input and output be strings?

**Comment by wu-clan** [comment]
Under normal circumstances, the secret key and encryption and decryption are bytes, not strings. hex() is a simple and efficient way to convert bytes into strings.

**Pull request merged**
