### PR TITLE
Remove the NoReturn return type

### PR DESCRIPTION
**Pull request by wu-clan**
PLR.

### CODE REVIEW

**Review by downdawn — APPROVED** [review]

**Comment by downdawn** [comment]
Why? Is there anything bad about it?

**Comment by wu-clan** [comment]
NoReturn should be used in infinite loop functions or system API functions, for regular returns, returning None is more friendly

**Comment by wu-clan** [comment]
Viewable：https://github.com/python/typing/pull/397

**Comment by wu-clan** [comment]
Look here: https://github.com/python/typing/issues/165

**Comment by downdawn** [comment]
OK

**Pull request merged**
