### PR TITLE
add login logs

### PR DESCRIPTION
**Pull request by wu-clan**
This is a pre-built version

Please note: This method will cause unnecessary delays in the login api

### CODE REVIEW

**Comment by wu-clan** [comment]
Hi, @downdawn 

Routine log entry may lead to unnecessary time loss? What do you think?

**Comment by wu-clan** [comment]
please review.

**Comment by downdawn** [comment]
> Hi, @downdawn
> 
> Routine log entry may lead to unnecessary time loss? What do you think?

The main delay is caused by the request url, can increase the timeout parameter

Log storage includes operations such as parsing ua and obtaining ip information, which can be extracted into tasks separately.

Consider whether to use BackgroundTasks

**Comment by wu-clan** [comment]
Okay.

The default timeout is 5s, and a minimum of 3s may be required to ensure operation.

**Comment by wu-clan** [comment]
Hi, @downdawn

Now it's elegant, please review.

**Review by downdawn — APPROVED** [review]

**Comment by downdawn** [comment]
LGTM

**Pull request merged**
