### PR TITLE
update to python3.10

### PR DESCRIPTION
**Pull request by downdawn**
[https://github.com/fastapi-practices/fastapi_best_architecture/pull/28](#28)

`ignore = ["F401"]`

Some need to ignore some don't

For example `from typing import Optional`

### CODE REVIEW

**Comment by wu-clan** [comment]
Can delete the global ignore=["F401"]

Add one by one to `per-file-ignore`

**Comment by downdawn** [comment]
OK, updated

**Comment by wu-clan** [comment]
Thanks，very nice.

**Review by wu-clan — COMMENTED** [review]
LGTM.

**Review by wu-clan — APPROVED** [review]
LGTM

**Review by wu-clan — APPROVED** [review]
LGTM.

**Pull request merged**
