### PR TITLE
Update roles and nickname fields to be optiona

### PR DESCRIPTION
**Pull request by wu-clan**
PLR.

### CODE REVIEW

**Comment by downdawn** [comment]
Do we no longer need to specify the department and role when creating a user?

**Comment by wu-clan** [comment]
No, if you register via the registration link in the login screen, it will only contain the username, password and email address.

If you add a user through the backend, you can select the department and role directly, and the department and role are useful for backend permission checking.

Here the front and back end you can understand: Users look at the information presentation interface, the background staff can see the management interface

**Comment by downdawn** [comment]
I understand what you mean. 
During registration, the frontend may only require the user to provide a username and password, and the department field can be left empty. However, there should be a default role assigned, otherwise, how would we allocate menus and permissions?

**Comment by wu-clan** [comment]
Departments and roles have to be assigned centrally by the administrator, as it's a matter of permissions

I don't think user registration should include departments and roles, but rather assign them at a later stage

**Comment by wu-clan** [comment]
Adding new users will be divided into two interfaces 

1. user registration will be realized through the login interface link, which does not contain fields related to permissions 
2. user addition will be realized through the back-end management, which contains department and role
selection

Ongoing, subject to prioritized review #191

**Comment by downdawn** [comment]
> 

When is the later stage allocation?
What default pages can a registered user see by default without a role assignment menu?

**Review by downdawn — APPROVED** [review]

**Comment by wu-clan** [comment]
This is exactly what the staff field is for, users don't support backend admin login by default, which means they can't see the backend admin interface unless the administrator assigns rights to it

When no role menu is assigned, we need to modify the front-end to set the dashboard to be owned by all users by default, to avoid displaying the 404 interface directly

**Comment by wu-clan** [comment]
This is designed to differentiate between external users and insiders, however, we will not be implementing anything related to the external user interface

**Pull request merged**
