### PR TITLE
opera_log_middleware method split

### PR DESCRIPTION
**Pull request by downdawn**
* opera_log_middleware method split
* extract ip and ua information
* added ua and ip information to login log and operation log

### CODE REVIEW

**Comment by wu-clan** [comment]
otherwise LGTM.

**Comment by downdawn** [comment]
please review.

**Review by wu-clan — COMMENTED** [review]
otherwise LGTM.

**Comment by downdawn** [comment]
fixed

**Comment by wu-clan** [comment]
Great!

**Review by wu-clan — APPROVED** [review]

**Pull request merged**
