### PR TITLE
update token handling logic

### PR DESCRIPTION
**Pull request by wu-clan**
WIP.

### CODE REVIEW

**Comment by wu-clan** [comment]
For related comments, please see: https://github.com/fastapi-practices/fastapi_best_architecture/discussions/44#discussioncomment-6032750

**Comment by wu-clan** [comment]
Hi, @downdawn 

Now it is ready for review.

**Comment by downdawn** [comment]
Hi, @wu-clan 
Please refer to the comment above.

**Comment by wu-clan** [comment]
> Hi, @wu-clan Please refer to the comment above.

The token processing logic there is controlled by the front end and should not be implemented in the back end, which is only responsible for the interface

**Comment by wu-clan** [comment]
Or did I miss your point?

**Comment by downdawn** [comment]
> Or did I miss your point?

The refresh token is not controlled by the front end, so it is not safe. unless there is a special need

**Comment by downdawn** [comment]
As discussed here, the first login returns the token and the refresh token, and the subsequent front-end can generate a new token based on the refresh token. We only need to provide an interface for generating a new token.
#44

**Comment by wu-clan** [comment]
Yes, but it already exists in this PR.

**Comment by downdawn** [comment]
Ok, we can merge this pr first, and make adjustments later

**Review by downdawn — APPROVED** [review]

**Comment by wu-clan** [comment]
Now it's ready

**Pull request merged**
