### PR TITLE
fix cors exception.

### PR DESCRIPTION
**Pull request by downdawn**
* fix get tree data exception.
* add nginx default server conf.
* fix menu test sql data.

### CODE REVIEW

**Comment by downdawn** [comment]
The cors problem of fastapi has not found a solution. [https://github.com/tiangolo/fastapi/issues/5263](https://github.com/tiangolo/fastapi/issues/5263)
So remove the CORS middleware and use nginx configuration to solve

**Comment by downdawn** [comment]
image
The back-end menu should be well controlled, and the front-end should not be further filtered

**Comment by downdawn** [comment]
pleace review

**Comment by wu-clan** [comment]
> The back-end menu should be well controlled, and the front-end should not be further filtered

I know this, but, no filter conditions should be added to the back-end tree data parsing

Reasons:

1. the menu display error should be borne by the super user, because that is caused by configuration errors 
2. to avoid dirty data in the menu 
3. can be controlled by the show switch to show or not

**Comment by wu-clan** [comment]
Also, nginx doesn't seem to be conducive to local debugging

**Comment by downdawn** [comment]
> > The back-end menu should be well controlled, and the front-end should not be further filtered

So the next step may be to implement the menu page first

**Comment by downdawn** [comment]
> Also, nginx doesn't seem to be conducive to local debugging

Yes, no solution found so far

**Comment by wu-clan** [comment]
The problem is perhaps better explained here: https://github.com/encode/starlette/issues/1175

The only thing I want to try is to put the exception interceptor before the middleware to register

**Comment by wu-clan** [comment]
> So the next step may be to implement the menu page first

I think so too.

**Comment by wu-clan** [comment]
I created a new PR #167 and temporarily fixed it and it is working

**Pull request closed without merging**
