### PR TITLE
add the get project config api

### PR DESCRIPTION
**Pull request by wu-clan**

### CODE REVIEW

**Comment by downdawn** [comment]
Can the password also be obtained? won't it be too dangerous

**Comment by wu-clan** [comment]
This api requires super administrator access, unless the account or token is leaked?

**Comment by wu-clan** [comment]
This should be just a temporary api.

**Comment by downdawn** [comment]
In any case, important information such as passwords should be avoided from being connected to the internet as much as possible, as unknown vulnerabilities cannot be ruled out.

**Comment by wu-clan** [comment]
Agreed

**Comment by wu-clan** [comment]
Hi, @downdawn 

What do you think about some of the database related?

E.g.:

host, post...

**Comment by downdawn** [comment]
What is the purpose of this API?

If we want to display it, we can desensitize the sensitive information.

**Comment by wu-clan** [comment]
As I said above, it is temporary and only for debugging.

I think it will be deleted later.

**Pull request merged**
