### PR TITLE
refactor routers

### PR DESCRIPTION
**Pull request by wu-clan**

### CODE REVIEW

**Comment by wu-clan** [comment]
please review.

**Comment by wu-clan** [comment]
Please note that this change will completely remove the deferred class view support and will use the function view exclusively

**Comment by wu-clan** [comment]
Pros: More centrally managed router

Disadvantages: not intuitive enough

**Comment by downdawn** [comment]
In this way, there is one more step in the development of the interface,and I believe we should consider a balance.

Maybe we can open a separate branch first

**Comment by wu-clan** [comment]
Getting the router to work the way it did, I decided to abandon the change

Yes, it became more cumbersome

**Pull request closed without merging**
